export enum EtapaWhatsappEnum {
  AVISO_VISTORIA_24H_CLIENTE = 'AVISO_VISTORIA_24H',
  AVISO_VISTORIA_24H_PROFISSIONAL = 'AVISO_VISTORIA_24H_PROFISSIONAL',
  CONFIRMACAO_ORCAMENTO = 'CONFIRMACAO_ORCAMENTO',
  AGRADECIMENTO_ORCAMENTO_CANCELADO = 'AGRADECIMENTO_ORCAMENTO_CANCELADO',
  AGRADECIMENTO_ORCAMENTO_ACEITO = 'AGRADECIMENTO_ORCAMENTO_ACEITO',
  AVISO_INSTALACAO_24H = 'AVISO_INSTALACAO_24H',
  AVISO_INSTALACAO_24H_PROFISSIONAL = 'AVISO_INSTALACAO_24H_PROFISSIONAL',
  PRIMEIRA_SATISFACAO = 'PRIMEIRA_SATISFACAO',
  SEGUNDA_SATISFACAO = 'SEGUNDA_SATISFACAO',
  TERCEIRA_SATISFACAO = 'TERCEIRA_SATISFACAO',
  ENCERRADO = 'ENCERRADO',
}